### PR TITLE
Remove duplicate agentsettings query from the middleware

### LINKED ISSUE #2: Duplicate agentsettings query in middleware
Currently the agent settings for a user gets queried twice per request. 

Once here:
https://github.com/django-otp/django-agent-trust/blob/f55014392b4927ddc161bf7f1d772626f2d7e0db/src/django_agent_trust/middleware.py#L34

And again:
https://github.com/django-otp/django-agent-trust/blob/f55014392b4927ddc161bf7f1d772626f2d7e0db/src/django_agent_trust/middleware.py#L49

Can be cached by setting the request.user.agentsettings via the return from get_or_create.

### PR DESCRIPTION
**Pull request by ThePumpingLemma**
This fixes https://github.com/django-otp/django-agent-trust/issues/2

### CODE REVIEW

**Comment by psagers** [comment]
I can't seem to find the documentation on `is_cached`; can you link to it?

Thanks

**Comment by ThePumpingLemma** [comment]
I don't think there are any docs AFAICT. Support was added in https://github.com/django/django/commit/bfb746f983aa741afa3709794e70f1e0ab6040b5 to fix this ticket https://code.djangoproject.com/ticket/16043

If there is a public/documented API for doing this, I can update the PR, but I am not aware of one.

**Comment by psagers** [comment]
Using an undocumented API—essentially a contradiction in terms—is questionable under the best of circumstances. I don't think we want to introduce that kind of risk for a minor performance optimization.

**Comment by ThePumpingLemma** [comment]
Only reference I could find to it referred to it as an internal API: https://code.djangoproject.com/ticket/31803. I think it is fine, but not my call.

I actually wrote the patch because there is a bug in the code. To reproduce:

1. Use a model manager to select related the agent settings with you user model
2. If a user is fetched and it does not have agent settings, the middleware creates it (https://github.com/django-otp/django-agent-trust/blob/43151a5c923abd9865723804bc84fb4665f399bb/src/django_agent_trust/middleware.py#L32)
3. Code fails in `_load_agent` when trying to access the cached property (https://github.com/django-otp/django-agent-trust/blob/43151a5c923abd9865723804bc84fb4665f399bb/src/django_agent_trust/middleware.py#L47)

This patch fixes that issue, but you can also `get_or_create` and assign the user unconditionally or refresh the user from the DB. I think the extra round trip to the DB for every request is less than ideal though.

**Comment by ThePumpingLemma** [comment]
We could also make it easier to override, e.g.:

```
def get_agentsettings(self, request):
    return AgentSettings.objects.get_or_create(user=request.user)

def __call__(self, request):
        if request.user.is_authenticated:
            agentsettings = self.get_agentsettings(request)
            request.agent = self._load_agent(agentsettings, request)
        else:
            request.agent = Agent.untrusted_agent(request.user)

        response = self.get_response(request)

        agent = getattr(request, 'agent', None)
        if agent and agent.user.is_authenticated:
            self._save_agent(agent, response)

        return response

    def _load_agent(self, agentsettings, request):
        cookie_name = self._cookie_name(request.user.get_username())
        max_age = self._max_cookie_age(agentsettings)
```

Then the client is free to change how the agent settings are fetched.

**Comment by psagers** [comment]
The change I just pushed should resolve the original issue with completely standard Django. If I'm understanding the bug you described, it should address that as well. If not, perhaps you'd like to write a test case that reproduces the bug and then we'll have something to work against.

Thanks

**Comment by ThePumpingLemma** [comment]
This should work. Thanks!

**Pull request closed without merging**
